name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # Use the Python version your project requires

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HG }}  # Use your repository secret named 'HG'
      run: |
        python -m pip install huggingface_hub
        huggingface-cli login --token $HF_TOKEN
        huggingface-cli repo delete aimalZahid/text-summarization-app --yes --token $HF_TOKEN || true
        huggingface-cli repo create aimalZahid/text-summarization-app --type=space --sdk=gradio --token $HF_TOKEN
        huggingface-cli upload . --repo-id aimalZahid/text-summarization-app --token $HF_TOKEN
